[package]
name = "graphics-rs"
version = "0.1.0"
edition = "2021"

[[example]]
name = "bresenham"
path = "bresenham/src/main.rs"

[dependencies]
fnv = "1.0.7"
piston = "0.53.2"
piston2d-graphics = "0.43.0"
piston2d-opengl_graphics = "0.82.0"
piston_window = "0.129.0"
rusttype = "0.9.3"
